### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by kruusamae** [unitartu-edu/carrot_follower#1]
Explain that this content has been created for ROSi algkursus (sisu.ut.ee/rosak).
Acknowledge the funding source: "Completed with the support by IT Acadamy Programme of Education and Youth Board of Estonia."

**Comment by sandra-schumann** [comment]
Added the corresponding info to the beginning of README.md

**Comment by kruusamae** [comment]
great! only one more small request. move the funding acknowledgement to the very bottom of the README. most people expect it to be there. also, feel free to link the logos from here: https://github.com/unitartu-remrob/.github/blob/main/profile/README.md

**Comment by sandra-schumann** [comment]
Is this version better?

**Comment by kruusamae** [comment]
yes, much. thanks!
